version: '3.8'
services:
  articles_db:
    image: postgres
    restart: always
    container_name: pizzeria_db
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=PizzaDelivery
    ports:
      - '5432:5432'
  users_db:
    image: postgres
    restart: always
    container_name: users_db
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=users
    ports:
      - '5431:5432'