// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package pizzas_db

import ()

type Pizza struct {
	PizzaID     int32   `json:"pizzaId"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type PizzaOrder struct {
	PizzaOrderID   int32   `json:"pizzaOrderId"`
	ShoppingCartID int32   `json:"shoppingCartId"`
	PizzaName      string  `json:"pizzaName"`
	PizzaPrice     float64 `json:"pizzaPrice"`
	Quantity       int32   `json:"quantity"`
}

type ShoppingCart struct {
	ShoppingCartID int32 `json:"shoppingCartId"`
	UserID         int32 `json:"userId"`
}
