// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package pizzas_db

import (
	"context"
)

type Querier interface {
	CreatePizza(ctx context.Context, arg CreatePizzaParams) (Pizza, error)
	DeletePizza(ctx context.Context, pizzaID int32) error
	GetAllPizzas(ctx context.Context) ([]Pizza, error)
	GetPizzaById(ctx context.Context, pizzaID int32) (Pizza, error)
	GetPizzaByName(ctx context.Context, name string) (Pizza, error)
	UpdatePizza(ctx context.Context, arg UpdatePizzaParams) (Pizza, error)
}

var _ Querier = (*Queries)(nil)
