// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package pizzas_db

import (
	"context"
)

type Querier interface {
	AddQuantityToOrderForExistingPizza(ctx context.Context, arg AddQuantityToOrderForExistingPizzaParams) (PizzaOrder, error)
	CreatePizza(ctx context.Context, arg CreatePizzaParams) (Pizza, error)
	CreatePizzaOrder(ctx context.Context, arg CreatePizzaOrderParams) (PizzaOrder, error)
	CreateShoppingCart(ctx context.Context, username string) (ShoppingCart, error)
	DeleteAllPizzasWithTheSameNameFromShoppingCart(ctx context.Context, arg DeleteAllPizzasWithTheSameNameFromShoppingCartParams) error
	DeletePizza(ctx context.Context, pizzaID int32) error
	GetAllOrdersByShoppingCartID(ctx context.Context, shoppingCartID int32) ([]PizzaOrder, error)
	GetAllPizzas(ctx context.Context) ([]Pizza, error)
	GetPizzaById(ctx context.Context, pizzaID int32) (Pizza, error)
	GetPizzaByName(ctx context.Context, name string) (Pizza, error)
	GetPizzaOrderByNameFromShoppingCart(ctx context.Context, arg GetPizzaOrderByNameFromShoppingCartParams) (PizzaOrder, error)
	GetShoppingCartByUsername(ctx context.Context, username string) (ShoppingCart, error)
	SubtractQuantityOfExistingPizzaFromOrder(ctx context.Context, arg SubtractQuantityOfExistingPizzaFromOrderParams) (PizzaOrder, error)
	UpdatePizza(ctx context.Context, arg UpdatePizzaParams) (Pizza, error)
	UpdatePizzaQuantityInShoppingCart(ctx context.Context, arg UpdatePizzaQuantityInShoppingCartParams) error
}

var _ Querier = (*Queries)(nil)
