// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (User, error)
	GetAccount(ctx context.Context, userID int32) (User, error)
}

var _ Querier = (*Queries)(nil)
