// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: service_pizzeria.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PizzeriaClient is the client API for Pizzeria service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PizzeriaClient interface {
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
}

type pizzeriaClient struct {
	cc grpc.ClientConnInterface
}

func NewPizzeriaClient(cc grpc.ClientConnInterface) PizzeriaClient {
	return &pizzeriaClient{cc}
}

func (c *pizzeriaClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/Pizzeria/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PizzeriaServer is the server API for Pizzeria service.
// All implementations must embed UnimplementedPizzeriaServer
// for forward compatibility
type PizzeriaServer interface {
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	mustEmbedUnimplementedPizzeriaServer()
}

// UnimplementedPizzeriaServer must be embedded to have forward compatible implementations.
type UnimplementedPizzeriaServer struct {
}

func (UnimplementedPizzeriaServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedPizzeriaServer) mustEmbedUnimplementedPizzeriaServer() {}

// UnsafePizzeriaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PizzeriaServer will
// result in compilation errors.
type UnsafePizzeriaServer interface {
	mustEmbedUnimplementedPizzeriaServer()
}

func RegisterPizzeriaServer(s grpc.ServiceRegistrar, srv PizzeriaServer) {
	s.RegisterService(&Pizzeria_ServiceDesc, srv)
}

func _Pizzeria_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PizzeriaServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pizzeria/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PizzeriaServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pizzeria_ServiceDesc is the grpc.ServiceDesc for Pizzeria service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pizzeria_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Pizzeria",
	HandlerType: (*PizzeriaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginUser",
			Handler:    _Pizzeria_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_pizzeria.proto",
}
