swagger: '2.0'
info:
  title: User Microservice API
  version: 1.0.0
  description: API for user registration and management.

paths:
  /signup:
    post:
      summary: User Registration
      description: Register a new user account.
      tags:
        - Users
      parameters:
        - name: body
          in: body
          description: User registration data
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                description: The username of the new user.
              email:
                type: string
                format: email
                description: The email address of the new user.
              password:
                type: string
                description: The password for the new user.
            required:
              - username
              - email
              - password
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request. Invalid input data
        '409':
          description: Conflict. User already exists
  /login:
    post:
      summary: User Login
      description: Authenticate and log in a user.
      tags:
        - Users
      parameters:
        - name: body
          in: body
          description: User login data
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                format: email
                description: The email address of the user.
              password:
                type: string
                description: The user's password.
            required:
              - email
              - password
      responses:
        '200':
          description: User logged in successfully
          schema:
            type: object
            properties:
              token:
                type: string
                description: Authentication token for the user's session
        '401':
          description: Unauthorized. Invalid credentials
